### ISSUE TITLE
Python 3.13 support

### ISSUE THREAD

**Issue by henriquegemignani** [henriquegemignani/PyQtDarkTheme#1]
With PySide 6.8.0.1 out, there's now a PySide version that supports 3.13. (6.8.0 crashes very hard with this package).

**Comment by henriquegemignani** [comment]
Lies, PySide 8.3.0 has requires python < 3.13 so that's a blocker for now

**Comment by bearsh** [comment]
PySide6==6.8.0.2 should support python 3.13

**Comment by rubin55** [comment]
@henriquegemignani I read [your pr](https://github.com/henriquegemignani/PyQtDarkTheme/pull/2) and I see this is fixed in 2.3.3, but 2.3.3 is not available in PyPi yet. When will 2.3.3 be pip installable?

**Comment by henriquegemignani** [comment]
I think what happened is the CI for releasing failed and I forgot to follow up on fixing it up. Thanks for the reminder

**Comment by rubin55** [comment]
@henriquegemignani do you have a timeframe on this? I just tried, but I'm still getting: `Because foo depends on pyqtdarktheme-fork (^2.3.3) which doesn't match any versions, version solving failed.`

**Comment by henriquegemignani** [comment]
I'm on holidays at the moment with no guaranteed time to look into it for a couple of weeks. I might be able to do it earlier but no guarantees.

**Comment by henriquegemignani** [comment]
Another error, again uploading :( https://github.com/henriquegemignani/PyQtDarkTheme/actions/runs/12583295748/job/35070538454

**Comment by rubin55** [comment]
I've tried `2.3.4`, but still no dice.

**Comment by henriquegemignani** [comment]
Not sure what's your issue with 2.3.4. It's [available in pypi](https://pypi.org/project/PyQtDarkTheme-fork/) and I have successfully installed it in a python 3.13 interpreter.

You'll need to provide more details of what's going on.

**Comment by rubin55** [comment]
Ah of course, I didn't read the error-output of `poetry lock` correctly. I have Python 3.13.1, and a project that has a dependency on pyqtdarktheme-fork. When I execute `poetry lock`, I get:

```
The current project's supported Python range (>=3.12,<4.0) is not compatible with some of the required packages Python requirement:
  - pyqtdarktheme-fork requires Python <3.14,>=3.8, so it will not be satisfied for Python >=3.14,<4.0

Because pyqtdarktheme-fork (2.3.4) requires Python <3.14,>=3.8
 and no versions of pyqtdarktheme-fork match >2.3.4,<3.0.0, pyqtdarktheme-fork is forbidden.
So, because tidal-dl-ng depends on pyqtdarktheme-fork (^2.3.4), version solving failed.
```

**Comment by henriquegemignani** [comment]
I don't use poetry that much, but it seems to be complaining about the maximum python version?

Tbh I don't even like bounding the upper version like this package does, might remove that in the future so it no longer needs a guaranteed yearly release.

**Comment by rubin55** [comment]
Yeah, personally, I really hate `poetry`, but I'm forced to deal with its insanity (i.e., every transitive dependency declaring which version of python it is compatible with.. erronuously) because some upstream open source stuff I maintain a package for uses it. Thanks for the help so far in any case.
